### ISSUE TITLE
Kohree VHP560 - Pairing mode?

### ISSUE THREAD

**Issue by kevinwells22** [DavinKD/SmartThings#1]
Hi, I have an Kohree VHP560 smart light bulb which I am trying to flash via OTT method to Tasmota, as I have done with many other devices, and trying to use tuya-convert, but I am stuck at 'put the device in pairing mode. On this page (https://github.com/arendst/Sonoff-Tasmota/wiki/Kohree-VHP560-Smart-Light-Compatible,-RGBCW-Wi-Fi-LED-Bulb-A19) I see you said "Easily flashed OTA", could you give me more info please?

**Comment by DavinKD** [comment]
Flashing questions should be addressed to the Tuya Convert folks.
