### ISSUE TITLE
Using this behind a CG-NAT

### ISSUE THREAD

**Issue by kaisax** [DavinKD/SmartThings#2]
Hi there,

I was curious if its possible to run this device handler/the MQTT bridge behind a CG-NAT (as in i dont have a dedicated IPv4 address).
Currently trying to run it with my local IP (192.168.x.x) doesn't seem to work

**Comment by DavinKD** [comment]
As long as your devices and the SmartThings hub are both on the same subnet, you should not have any issues.  If they're not, you'll need to do some kind of firewall rules and/or NAT.  That's out of scope for this codebase, though.
